version: '3.8'
services:
    wyze-bridge:
        restart: always
        # network_mode: host
        ports:
            - 1935:1935
            - 8554:8554
            - 8888:8888
        build: 
            context: ./app
            # dockerfile: Dockerfile.arm
        environment:
            - WYZE_EMAIL=
            - WYZE_PASSWORD=
